pipeline {
    
    agent {
    	docker { 
		image 'maven:3.6.1-jdk-8-alpine'
		args '-v $HOME/.m2:/root/.m2'
	}
    }
    
    tools {
    	maven 'Maven 3.6.1'
    }

    stages{
        stage('build'){
	    when{
		changeset "**/worker/**"
		}
            steps{
                echo 'Build worker app.'
		dir('worker'){
			sh 'mvn compile'
		}
            }
        }
        stage('test'){
	    when{
		changeset "**/worker/**"
		}
            steps{
                echo 'Running unit test on worker app.'
		dir('worker'){
			sh 'mvn clean test'
		}
            }
        }
        stage('package'){
	    when{
	    	branch 'master'
		changeset "**/worker/**"
		}
            steps{
                echo 'Package worker app.'
		dir('worker'){
			sh 'mvn package -DskipTests'
			archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
		}
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline for worker is completed.'
        }
    }
}
